// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGqvJRicFsgBB66OtFsnaBpZPhT4LpO9g',
    appId: '1:950481483134:web:2e4f9b3c157fa2c890ef2f',
    messagingSenderId: '950481483134',
    projectId: 'gdlapp-95dfa',
    authDomain: 'gdlapp-95dfa.firebaseapp.com',
    storageBucket: 'gdlapp-95dfa.appspot.com',
    measurementId: 'G-DJ7455454Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRbhxaWSOk5vP19G7dFzk-WMAfcKCvTEc',
    appId: '1:950481483134:android:d81ec7d2615e5d5890ef2f',
    messagingSenderId: '950481483134',
    projectId: 'gdlapp-95dfa',
    storageBucket: 'gdlapp-95dfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKfW7rcmDaTQi30M-3VFKQutH2xZBZYB0',
    appId: '1:950481483134:ios:ada370030368ceae90ef2f',
    messagingSenderId: '950481483134',
    projectId: 'gdlapp-95dfa',
    storageBucket: 'gdlapp-95dfa.appspot.com',
    iosClientId: '950481483134-7odpg5v1r1pjgrhdsvdps8fpoucpbb7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicativoGdlV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKfW7rcmDaTQi30M-3VFKQutH2xZBZYB0',
    appId: '1:950481483134:ios:ada370030368ceae90ef2f',
    messagingSenderId: '950481483134',
    projectId: 'gdlapp-95dfa',
    storageBucket: 'gdlapp-95dfa.appspot.com',
    iosClientId: '950481483134-7odpg5v1r1pjgrhdsvdps8fpoucpbb7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicativoGdlV2',
  );
}
